### ISSUE TITLE
Routing lib

### ISSUE THREAD

**Issue by corporatepiyush** [dubiousdavid/dominator#2]
Is it possible to integrate any routing lib like "secretary" for SPA ? An example would be really helpful.

**Comment by dubiousdavid** [comment]
Sure. You could have a "page" key in your model and create a writeable signal via `sig/write-port` (see Wikipedia example). Then simply put a value onto the write-port you created with the page that corresponds to the matched route. From there it's just a matter of having your view rendering logic dependent on that "page" key.
